# -*- coding: utf-8 -*-
"""titanic_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDZV_LkEZeX8b7eVeoWwSTVih4fHQoWP
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def load_and_explore_titanic():
    print("Loading Titanic dataset...")
    url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
    df = pd.read_csv(url)

    print("\n--- Dataset Info & Missing Values ---")
    print(df.info())
    print("\nMissing values per column:")
    print(df.isnull().sum())

    return df

def clean_and_feature_engineer(df):
    print("\nCleaning data and engineering features...")

    # Fill missing Age with median
    df['Age'] = df['Age'].fillna(df['Age'].median())

    # Fill missing Embarked with mode
    df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

    # Drop columns with too many missing values or unhelpful identifiers
    df = df.drop(columns=['Cabin', 'Ticket', 'Name', 'PassengerId'])

    # Convert categorical variables to numeric
    df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
    df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

    print("Data cleaning complete!")
    return df

def train_and_evaluate_model(df):
    print("\nTraining Random Forest Classifier model...")

    X = df.drop(columns=['Survived'])
    y = df['Survived']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    print("\n--- Model Evaluation Results ---")
    print(f"Accuracy Score: {accuracy_score(y_test, y_pred):.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nFeature Importances:")
    importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
    print(importances)

    return model

if __name__ == "__main__":
    titanic_df = load_and_explore_titanic()
    cleaned_df = clean_and_feature_engineer(titanic_df)
    trained_model = train_and_evaluate_model(cleaned_df)