# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS_eleJnTQIFRaVL2AEs0uZnJt6H1mx3
"""

from typing import TypedDict
from fastapi import FastAPI
from langgraph.graph import END, StateGraph
pydantic_v1_compat = True  # Ensures compatibility across versions

# 1. Initialize FastAPI app
app = FastAPI(
    title="Zepto Support Assistant",
    description="A GenAI-powered support assistant built with FastAPI and LangGraph",
    version="1.0"
)

# 2. Define the State for LangGraph workflow
class SupportState(TypedDict):
    query: str
    category: str
    response: str

# 3. Define Graph Nodes (Workflow Logic)
def classify_query(state: SupportState):
    query = state["query"].lower()
    if "delivery" in query or "time" in query or "late" in query:
        category = "Delivery Issue"
    elif "refund" in query or "money" in query or "return" in query:
        category = "Refund / Payment"
    else:
        category = "General Inquiry"
    return {"category": category}

def generate_response(state: SupportState):
    category = state["category"]
    query = state["query"]

    if category == "Delivery Issue":
        resp = f"We are sorry for the delay regarding your query: '{query}'. Our delivery partner has been notified and will reach out shortly."
    elif category == "Refund / Payment":
        resp = f"Regarding your payment query ('{query}'), refunds typically process within 3-5 business days to your original payment method."
    else:
        resp = f"Thank you for contacting Zepto Support! We have received your message: '{query}' and our team is looking into it."

    return {"response": resp}

# 4. Build the LangGraph Workflow
workflow = StateGraph(SupportState)
workflow.add_node("classifier", classify_query)
workflow.add_node("responder", generate_response)

workflow.set_entry_point("classifier")
workflow.add_edge("classifier", "responder")
workflow.add_edge("responder", END)

support_graph = workflow.compile()

# 5. Define FastAPI Endpoint
@app.post("/chat")
def chat_with_assistant(query: str):
    # Run the query through our LangGraph state machine
    initial_state = {"query": query, "category": "", "response": ""}
    final_state = support_graph.invoke(initial_state)

    return {
        "user_query": final_state["query"],
        "detected_category": final_state["category"],
        "support_response": final_state["response"]
    }

@app.get("/")
def home():
    return {"message": "Welcome to the Zepto Support Assistant API! Send a POST request to /chat?query=your_question"}