# -*- coding: utf-8 -*-
"""pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylXVVW5clAey_RSa5kxFLkWus1NJpkA0
"""

import sqlite3
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

# Constants for Fixed Rate Conversion (Project Baseline)
GBP_TO_INR = 105.50
BASE_URL = "http://books.toscrape.com/"

def scrape_books():
    print("Starting scraping from books.toscrape.com...")
    response = requests.get(BASE_URL)
    response.encoding = 'utf-8'  # Fix encoding issues for currency symbols
    response.raise_for_status()
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find categories from the sidebar
    category_tags = soup.select('.side_categories ul.nav-list ul li a')

    categories_data = []
    for cat in category_tags:
        cat_name = cat.text.strip()
        cat_link = BASE_URL + cat['href']
        categories_data.append({'name': cat_name, 'url': cat_link})

    books_data = []
    # Scrape at least 3 distinct categories to get >= 60 books
    for cat in categories_data[:3]:
        cat_name = cat['name']
        cat_page = requests.get(cat['url'])
        cat_page.encoding = 'utf-8'
        cat_soup = BeautifulSoup(cat_page.text, 'html.parser')

        products = cat_soup.select('.product_pod')
        for prod in products:
            title = prod.h3.a['title']
            price_text = prod.select_one('.price_color').text

            # Robustly extract digits and decimal point only (e.g., 'Â£45.17' -> 45.17)
            price_numeric = re.sub(r'[^\d.]', '', price_text)
            price_gbp = float(price_numeric)

            rating_map = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
            star_class = prod.select_one('.star-rating')['class'][1]
            rating = rating_map.get(star_class, 0)

            avail_text = prod.select_one('.availability').text.strip()
            in_stock = 1 if 'In stock' in avail_text else 0

            books_data.append({
                'title': title,
                'price_gbp': price_gbp,
                'rating': rating,
                'in_stock': in_stock,
                'category_name': cat_name
            })

    df_books = pd.DataFrame(books_data)
    print(f"Successfully scraped {len(df_books)} books across {df_books['category_name'].nunique()} categories.")
    return df_books

def clean_and_transform(df):
    print("Cleaning and transforming data...")
    df['price_inr'] = df['price_gbp'] * GBP_TO_INR
    df['price_gbp'] = df['price_gbp'].astype(float)
    df['rating'] = df['rating'].astype(int)
    df['in_stock'] = df['in_stock'].astype(int)
    return df

def store_in_sqlite(df):
    db_path = 'zepto_books.db'
    print(f"Storing data into SQLite database at {db_path}...")
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS categories (
            category_id INTEGER PRIMARY KEY AUTOINCREMENT,
            category_name TEXT UNIQUE
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS books (
            book_id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT,
            price_gbp REAL,
            price_inr REAL,
            rating INTEGER,
            in_stock INTEGER,
            category_id INTEGER,
            FOREIGN KEY (category_id) REFERENCES categories(category_id)
        )
    ''')

    unique_categories = df['category_name'].unique()
    for cat in unique_categories:
        cursor.execute('INSERT OR IGNORE INTO categories (category_name) VALUES (?)', (cat,))

    conn.commit()

    cat_df = pd.read_sql('SELECT category_id, category_name FROM categories', conn)
    cat_mapping = dict(zip(cat_df['category_name'], cat_df['category_id']))
    df['category_id'] = df['category_name'].map(cat_mapping)

    df[['title', 'price_gbp', 'price_inr', 'rating', 'in_stock', 'category_id']].to_sql(
        'books', conn, if_exists='replace', index=False
    )
    conn.close()
    print("Database storage complete!")

def run_queries():
    db_path = 'zepto_books.db'
    conn = sqlite3.connect(db_path)

    print("\n--- Executing Required SQL Queries ---")

    print("\n1. Books with rating = 5:")
    q1 = pd.read_sql("SELECT title, price_gbp, rating FROM books WHERE rating = 5 LIMIT 5", conn)
    print(q1)

    print("\n2. Top 5 cheapest books:")
    q2 = pd.read_sql("SELECT title, price_gbp FROM books ORDER BY price_gbp ASC LIMIT 5", conn)
    print(q2)

    print("\n3. Distinct ratings available:")
    q3 = pd.read_sql("SELECT DISTINCT rating FROM books ORDER BY rating DESC", conn)
    print(q3)

    print("\n4. Books with price between 10 and 20 GBP:")
    q4 = pd.read_sql("SELECT title, price_gbp FROM books WHERE price_gbp BETWEEN 10 AND 20 LIMIT 5", conn)
    print(q4)

    print("\n5. JOIN Query: Books with their Category Names:")
    join_query = """
        SELECT b.title, c.category_name, b.price_gbp, b.rating
        FROM books b
        JOIN categories c ON b.category_id = c.category_id
        LIMIT 5
    """
    q5_sql = pd.read_sql(join_query, conn)
    print(q5_sql)

    print("\n--- Verifying pd.read_sql vs pd.merge equivalence ---")
    books_df = pd.read_sql("SELECT * FROM books", conn)
    cats_df = pd.read_sql("SELECT * FROM categories", conn)

    merged_pandas = pd.merge(books_df, cats_df, on='category_id', how='inner')
    merged_pandas_subset = merged_pandas[['title', 'category_name', 'price_gbp', 'rating']].head(5)

    print("Pandas Merge Result:")
    print(merged_pandas_subset)

    conn.close()

if __name__ == "__main__":
    df = scrape_books()
    df_clean = clean_and_transform(df)
    store_in_sqlite(df_clean)
    run_queries()